import { createReadStream } from 'node:fs'
import fs from 'node:fs/promises'
import path from 'node:path'
import { randomUUID } from 'node:crypto'

/**
 * STORAGE DRIVER CONTRACT
 * Any driver (local disk now, Google Drive later) implements these four methods and nothing else:
 *
 *   save({ tempPath, ext, folder }) -> Promise<{ key }>      move/upload a finished temp file, return an opaque key
 *   stat(key)                       -> Promise<{ size }>     throws if the file is gone
 *   createReadStream(key, { start, end }) -> Readable        inclusive byte range, for HTTP Range requests
 *   remove(key)                     -> Promise<void>         idempotent
 *
 * Nothing above this layer knows about paths, folders or Drive file ids; they only hold { driver, key }.
 * A Drive driver would map `key` to a Drive file id, upload from tempPath in save(), and use
 * files.get(alt=media) with a Range header for createReadStream().
 */
export function createLocalDriver(rootDir) {
  const root = path.resolve(rootDir)

  // Keys are generated by us, but never let one escape the storage root.
  const resolveKey = (key) => {
    const full = path.resolve(root, key)
    if (full !== root && !full.startsWith(root + path.sep)) throw new Error('Invalid storage key')
    return full
  }

  return {
    name: 'local',
    tempDir: path.join(root, 'tmp'),

    async init() {
      await fs.mkdir(path.join(root, 'tmp'), { recursive: true })
    },

    async save({ tempPath, ext = '', folder }) {
      const key = `${folder}/${randomUUID()}${ext}`
      const destination = resolveKey(key)
      await fs.mkdir(path.dirname(destination), { recursive: true })
      try {
        await fs.rename(tempPath, destination)
      } catch (error) {
        if (error.code !== 'EXDEV') throw error // temp dir on another disk: copy instead
        await fs.copyFile(tempPath, destination)
        await fs.unlink(tempPath)
      }
      return { key }
    },

    async stat(key) {
      const { size } = await fs.stat(resolveKey(key))
      return { size }
    },

    createReadStream: (key, range) => createReadStream(resolveKey(key), range),

    async remove(key) {
      await fs.unlink(resolveKey(key)).catch((error) => { if (error.code !== 'ENOENT') throw error })
    },
  }
}
