import { useState } from 'react'
import { Eyebrow, SectionHeading, VideoArtwork } from '../components/ui'
import { mockCategories, mockLessons } from '../mock/data'

const tones = { yellow: 'bg-[#f1d67d]', blue: 'bg-[#b8d0d5]', red: 'bg-[#e9a28c]', green: 'bg-[#b9cdbd]' }
const shell = 'mx-auto w-[calc(100%-38px)] max-w-[1160px] lg:w-[calc(100%-64px)]'

export default function CategoryBrowser({ categoryId, navigate, openLesson }) {
  const category = mockCategories.find((item) => item.id === categoryId) || mockCategories[0]
  const [query, setQuery] = useState('')
  const [level, setLevel] = useState('All levels')
  const [sort, setSort] = useState('Newest first')
  const lessons = mockLessons.filter((lesson) => lesson.category === category.id).filter((lesson) => level === 'All levels' || lesson.level === level).filter((lesson) => lesson.title.toLowerCase().includes(query.toLowerCase())).sort((first, second) => sort === 'Shortest first' ? first.duration.localeCompare(second.duration) : second.id - first.id)
  const levels = ['All levels', ...new Set(mockLessons.filter((lesson) => lesson.category === category.id).map((lesson) => lesson.level))]

  return <main className="pb-20"><div className={`${shell} flex gap-3 pt-10 text-xs text-[#8b867e]`}><button onClick={() => navigate('home')}>Library</button><span>/</span><b className="font-normal text-[#282824]">{category.label}</b></div><section className={`${shell} flex flex-col justify-between gap-8 border-b border-[#ded8cd] py-16 sm:flex-row sm:items-end`}><div><Eyebrow>Learning path · {category.count}</Eyebrow><h1 className="font-serif text-6xl leading-none">{category.label}<br /><em className="text-[#e3533d]">starts here.</em></h1></div><p className="max-w-xs text-sm leading-6 text-[#77736c]">{category.copy}</p></section><section className={`${shell} pt-16`}><SectionHeading eyebrow={`${lessons.length} lessons`} title="Pick a lesson." action={<div className="flex flex-wrap justify-end gap-2 text-xs"><select value={sort} onChange={(event) => setSort(event.target.value)} className="border-b border-[#d7d0c3] bg-transparent px-1 py-2 outline-none"><option>Newest first</option><option>Shortest first</option></select><select value={level} onChange={(event) => setLevel(event.target.value)} className="border-b border-[#d7d0c3] bg-transparent px-1 py-2 outline-none">{levels.map((item) => <option key={item}>{item}</option>)}</select></div>} /><label className="mb-8 block max-w-sm text-xs text-[#77736c]">Search lessons<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try 'introduction'" className="mt-2 block w-full border-b border-[#d7d0c3] bg-transparent py-3 outline-none focus:border-[#e3533d]" /></label>{lessons.length ? <div className="grid gap-8 md:grid-cols-3">{lessons.map((lesson, index) => <button key={lesson.id} className="text-left" onClick={() => openLesson(lesson)}><VideoArtwork lesson={lesson} className={`h-64 ${tones[category.tone]}`}><span className="absolute left-4 top-4 text-xs text-white">{String(index + 1).padStart(2, '0')}</span><i className="absolute bottom-4 right-4 grid h-10 w-10 place-items-center rounded-full bg-[#f6f2e9] text-xs not-italic text-[#e3533d]">▶</i></VideoArtwork><p className="mt-4 text-[10px] uppercase tracking-widest text-[#908b81]">{lesson.level} · {lesson.duration}</p><h3 className="mt-2 font-serif text-2xl">{lesson.title}</h3><span className="mt-3 block text-xs text-[#e3533d]">Open lesson ↗</span></button>)}</div> : <div className="border-t border-[#d7d0c3] py-12 text-sm text-[#77736c]">No lessons match those filters. <button className="text-[#e3533d]" onClick={() => { setQuery(''); setLevel('All levels') }}>Clear filters</button></div>}</section></main>
}
